services:
  gmod-server:
    build: .
    container_name: ionrp-server
    restart: unless-stopped
    
    env_file:
      - .env.default
      - .env
    
    # Port mappings
    ports:
      - "27015:27015/udp"  # Game server port
      - "27015:27015/tcp"  # RCON port
    
    # Environment variables
    # environment:
    #   - GMOD_HOSTNAME=${SERVER_HOSTNAME}
    #   - GMOD_GAMEMODE=${SERVER_GAMEMODE}
    #   - GMOD_PORT=${SERVER_PORT}
    #   - GMOD_MAXPLAYERS=${SERVER_MAXPLAYERS}
    #   - GMOD_MAP=${SERVER_MAP}
    #   - GMOD_STEAMTOKEN=${STEAM_TOKEN:-}
    
    # Bind mounts
    volumes:
      # Mount the ionrp gamemode into the server's gamemodes folder
      - ./:/home/steam/gmodserver/garrysmod/gamemodes/ionrp:ro
      
      # Mount server.cfg
      - ./docker/server.cfg:/home/steam/gmodserver/garrysmod/cfg/server.cfg:ro
      
      # Persistent data volumes (optional - uncomment if you want to persist data)
      - gmod-data:/home/steam/gmodserver/garrysmod/data
      - gmod-addons:/home/steam/gmodserver/garrysmod/addons
      - gmod-logs:/home/steam/gmodserver/garrysmod/logs
      - workshop_cache:/home/steam/gmodserver/garrysmod/cache
      - workshop_content:/home/steam/gmodserver/garrysmod/steamapps/workshop
      - steam_cache:/home/steam/gmodserver/steam_cache

      # MySQL socket for direct database connection
      - mysql-socket:/var/run/mysqld
    
    # Resource limits (optional)
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4G
        reservations:
          cpus: '1'
          memory: 2G
    
    # Interactive terminal
    stdin_open: true
    tty: true
    
    # Network dependencies
    depends_on:
      - mariadb
    
    # Connect to internal network
    networks:
      - ionrp-network

  mariadb:
    image: mariadb:11.2
    container_name: ionrp-mariadb
    restart: unless-stopped

    env_file:
      - .env.default
      - .env
    
    # Environment variables for database setup
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASS:-ionrp_root_password_change_me}
      - MYSQL_DATABASE=${DB_NAME:-ionrp}
      - MYSQL_USER=${DB_USER:-ionrp}
      - MYSQL_PASSWORD=${DB_PASS:-ionrp}
      - MARIADB_AUTO_UPGRADE=1
    
    # Persist database data
    volumes:
      - mariadb-data:/var/lib/mysql
      - mysql-socket:/var/run/mysqld
    
    # Only accessible within the docker network (not exposed to host)
    networks:
      - ionrp-network
    
    # Health check
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: ionrp-phpmyadmin
    restart: unless-stopped
    
    env_file:
      - .env.default
      - .env
    
    # Port mapping - access at http://localhost:27880
    ports:
      - "27880:80"
    
    # Environment variables
    environment:
      - PMA_HOST=${DB_HOST:-mariadb}
      - PMA_PORT=${DB_PORT:-3306}
      - PMA_USER=${DB_USER:-ionrp}
      - PMA_PASSWORD=${DB_PASSWORD:-ionrp}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASS:-ionrp_root_password_change_me}
      - UPLOAD_LIMIT=300M
    
    # Connect to internal network
    networks:
      - ionrp-network
    
    # Depends on database
    depends_on:
      mariadb:
        condition: service_healthy

# Networks
networks:
  ionrp-network:
    driver: bridge

# Volumes
volumes:
  gmod-data:
  gmod-addons:
  gmod-logs:
  workshop_cache:
  workshop_content:
  steam_cache:
  mariadb-data:
  mysql-socket:
